from pathlib import Path

MIN_CHARS = 80
BATCH_SIZE = 20
_RETRY_ATTEMPTS = 3
_RETRY_DELAY = 2.0 
THRESHOLD = 0.6
PAGE_SIZE = 5000
MAX_CHARS = 500
OVERLAP_SENTENCES = 1
OLLAMA_TIMEOUT = 2
AGENT_DIR = Path(".agent").resolve()
USER_PROFILE_FILE = "USER.md"
SOUL_FILE = "SOUL.md"
CONSOLIDATE_EVERY_N = 20
